### PR TITLE
Add weather station in instrumentation page

### LINKED ISSUE #15: Add weather station information on Instrumentation page

### PR DESCRIPTION
**Pull request by IoannisSifnaios**
closes #15

### CODE REVIEW

**Comment by IoannisSifnaios** [comment]
@AdamRJensen I could not find a nice way to resize the images. I think that the weather station image is a bit too large...

**Comment by AdamRJensen** [comment]
> @AdamRJensen I could not find a nice way to resize the images. I think that the weather station image is a bit too large...

Just Google reduce image size and the choose one of the many free options

**Comment by IoannisSifnaios** [comment]
> > @AdamRJensen I could not find a nice way to resize the images. I think that the weather station image is a bit too large...
> 
> Just Google reduce image size and the choose one of the many free options

It is now fixed and ready for review

**Comment by AdamRJensen** [comment]
Could you add units for Rain? I guess its in the weather station documentation

**Review by AdamRJensen — APPROVED** [review]
LGTM

**Pull request merged**
